title: A designers guide to Github
author: @ajashams
email: ajashams@github.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about what it's like working at Github as a site designer with no code or development experience. 

# social links
twitter_username: ajalee # DO NOT include the @ character, or else the build will fail!
github_username:  ajashams # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
